/* Source: /home/vikum_02/JacFit/components/Dashboard.cl.jac */
import {__jacJsx, __jacSpawn} from "@jac/runtime";
function Dashboard(props) {
  const {daily, progress} = props;
  function statCard(props) {
    const {label, value, color} = props;
    return __jacJsx("div", {"style": {"background": "#fff", "borderRadius": "12px", "padding": "20px", "flex": "1", "textAlign": "center", "boxShadow": "0 1px 3px rgba(0,0,0,0.1)"}}, [__jacJsx("p", {"style": {"color": "#6b7280", "fontSize": "13px", "marginBottom": "6px"}}, [label]), __jacJsx("p", {"style": {"color": color, "fontSize": "1.8rem", "fontWeight": "700"}}, [value])]);
  }
  return __jacJsx("div", {}, [((daily && __jacJsx("div", {}, [__jacJsx("h2", {"style": {"marginBottom": "16px", "color": "#166534"}}, ["Today — ", daily["date"]]), __jacJsx("div", {"style": {"display": "flex", "gap": "16px", "marginBottom": "24px"}}, [statCard("Calories In", (String(daily["calories_in"]) + " kcal"), "#16a34a"), statCard("Calories Out", (String(daily["calories_out"]) + " kcal"), "#dc2626"), statCard("Net", (String(daily["net"]) + " kcal"), ((daily["net"] > 0) ? "#dc2626" : "#16a34a"))]), __jacJsx("div", {"style": {"display": "flex", "gap": "16px", "marginBottom": "24px"}}, [__jacJsx("div", {"style": {"background": "#fff", "borderRadius": "12px", "padding": "20px", "flex": "1", "boxShadow": "0 1px 3px rgba(0,0,0,0.1)"}}, [__jacJsx("h3", {"style": {"color": "#166534", "marginBottom": "12px"}}, ["Meals"]), (daily["meals"] ? daily["meals"].map(m => __jacJsx("p", {"key": m, "style": {"padding": "6px 0", "borderBottom": "1px solid #f0fdf4", "color": "#374151"}}, [m])) : __jacJsx("p", {"style": {"color": "#9ca3af"}}, ["No meals logged"]))]), __jacJsx("div", {"style": {"background": "#fff", "borderRadius": "12px", "padding": "20px", "flex": "1", "boxShadow": "0 1px 3px rgba(0,0,0,0.1)"}}, [__jacJsx("h3", {"style": {"color": "#166534", "marginBottom": "12px"}}, ["Exercises"]), (daily["exercises"] ? daily["exercises"].map(e => __jacJsx("p", {"key": e, "style": {"padding": "6px 0", "borderBottom": "1px solid #f0fdf4", "color": "#374151"}}, [e])) : __jacJsx("p", {"style": {"color": "#9ca3af"}}, ["No exercises logged"]))])])])) || __jacJsx("p", {"style": {"color": "#9ca3af"}}, ["No data for today yet."])), ((progress && __jacJsx("div", {"style": {"background": "#fff", "borderRadius": "12px", "padding": "20px", "boxShadow": "0 1px 3px rgba(0,0,0,0.1)"}}, [__jacJsx("h3", {"style": {"color": "#166534", "marginBottom": "12px"}}, ["Progress"]), __jacJsx("p", {"style": {"color": "#374151", "marginBottom": "6px"}}, ["Current: ", __jacJsx("strong", {}, [String(progress["current_weight"]), " kg"])]), __jacJsx("p", {"style": {"color": "#374151", "marginBottom": "6px"}}, ["Target: ", __jacJsx("strong", {}, [String(progress["target_weight"]), " kg"])]), __jacJsx("p", {"style": {"color": "#374151", "marginBottom": "6px"}}, ["Goal: ", __jacJsx("strong", {}, [progress["goal_type"]])]), __jacJsx("p", {"style": {"color": "#374151"}}, ["Est. days to goal: ", __jacJsx("strong", {}, [String(progress["estimated_days_to_goal"])])])])) || null)]);
}
export {Dashboard};
if (typeof globalThis !== "undefined") { if (!globalThis.__jacEndpointEffects__) globalThis.__jacEndpointEffects__ = {}; Object.assign(globalThis.__jacEndpointEffects__, {"func:Dashboard": {"is_writer": false, "touches": ["*"]}}); };
//# sourceMappingURL=Dashboard.js.map
