/* Source: /home/vikum_02/JacFit/components/WeeklyTrend.cl.jac */
import {__jacJsx, __jacSpawn} from "@jac/runtime";
function WeeklyTrendView(props) {
  const {data} = props;
  return __jacJsx("div", {}, [((data && __jacJsx("div", {}, [__jacJsx("h2", {"style": {"color": "#166534", "marginBottom": "8px"}}, ["Weekly Trend"]), __jacJsx("p", {"style": {"color": "#6b7280", "marginBottom": "24px", "fontSize": "14px"}}, [data["consistency"]]), __jacJsx("div", {"style": {"background": "#fff", "borderRadius": "12px", "overflow": "hidden", "boxShadow": "0 1px 3px rgba(0,0,0,0.1)", "marginBottom": "24px"}}, [__jacJsx("div", {"style": {"display": "grid", "gridTemplateColumns": "1fr 1fr 1fr 1fr", "background": "#166534", "padding": "12px 16px"}}, [__jacJsx("span", {"style": {"color": "#fff", "fontWeight": "700", "fontSize": "13px"}}, ["Date"]), __jacJsx("span", {"style": {"color": "#fff", "fontWeight": "700", "fontSize": "13px"}}, ["In (kcal)"]), __jacJsx("span", {"style": {"color": "#fff", "fontWeight": "700", "fontSize": "13px"}}, ["Out (kcal)"]), __jacJsx("span", {"style": {"color": "#fff", "fontWeight": "700", "fontSize": "13px"}}, ["Net"])]), data["days"].map(d => __jacJsx("div", {"key": d["date"], "style": {"display": "grid", "gridTemplateColumns": "1fr 1fr 1fr 1fr", "padding": "12px 16px", "borderBottom": "1px solid #f0fdf4"}}, [__jacJsx("span", {"style": {"color": "#374151", "fontSize": "14px"}}, [String(d["date"])]), __jacJsx("span", {"style": {"color": "#16a34a", "fontSize": "14px"}}, [String(d["calories_in"])]), __jacJsx("span", {"style": {"color": "#dc2626", "fontSize": "14px"}}, [String(d["calories_out"])]), __jacJsx("span", {"style": {"fontSize": "14px"}}, [String(d["net"])])]))]), __jacJsx("div", {"style": {"background": "#fff", "borderRadius": "12px", "padding": "20px", "boxShadow": "0 1px 3px rgba(0,0,0,0.1)"}}, [__jacJsx("p", {"style": {"color": "#374151"}}, ["Avg Daily Intake: ", __jacJsx("strong", {}, [String(data["avg_daily_intake"]), " kcal"])])])])) || __jacJsx("p", {"style": {"color": "#9ca3af"}}, ["No weekly data yet."]))]);
}
export {WeeklyTrendView};
if (typeof globalThis !== "undefined") { if (!globalThis.__jacEndpointEffects__) globalThis.__jacEndpointEffects__ = {}; Object.assign(globalThis.__jacEndpointEffects__, {"func:WeeklyTrendView": {"is_writer": false, "touches": ["*"]}}); };
//# sourceMappingURL=WeeklyTrend.js.map
